name = "Tufte"
license = "MIT"
licenselink = "https://github.com/slashformotion/hugo-tufte/blob/master/LICENSE.md"
description = "A minimalist blog theme using Tufte-css."
homepage = "http://github.com/slashformotion/hugo-tufte"
demo = "https://slashformotion.github.io/hugo-tufte/"
tags = ["blog", "tufte", "minimal", 'light', "personal"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.83

authors = [
  {name = "Shawn O'Hare", homepage = "http://www.shawnohare.com"},
  {name = "Slashformotion", homepage = "https://github.com/slashformotion"}
]
